# Generated by Django 2.1 on 2019-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
