# Generated by Django 2.1 on 2019-01-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_auto_20190114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/'),
        ),
    ]
