# Generated by Django 2.1 on 2019-01-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_auto_20190114_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
